/********************************************************************
* /home/dhynds/tbcode/src/EventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/dhynds/tbcode/src/EventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEventDict();
extern void G__cpp_setup_inheritanceEventDict();
extern void G__cpp_setup_typetableEventDict();
extern void G__cpp_setup_memvarEventDict();
extern void G__cpp_setup_globalEventDict();
extern void G__cpp_setup_memfuncEventDict();
extern void G__cpp_setup_funcEventDict();
extern void G__set_cpp_environmentEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/dhynds/tbcode/src/TestBeamEvent.h"
#include "/home/dhynds/tbcode/src/TestBeamEventElement.h"
#include "/home/dhynds/tbcode/src/RowColumnEntry.h"
#include "/home/dhynds/tbcode/src/FEI4RowColumnEntry.h"
#include "/home/dhynds/tbcode/src/TestBeamDataSummary.h"
#include "/home/dhynds/tbcode/src/TDCFrame.h"
#include "/home/dhynds/tbcode/src/TDCTrigger.h"
#include "/home/dhynds/tbcode/src/SystemOfUnits.h"
#include "/home/dhynds/tbcode/src/PhysicalConstants.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventDictLN_TClass;
extern G__linked_taginfo G__EventDictLN_TBuffer;
extern G__linked_taginfo G__EventDictLN_TMemberInspector;
extern G__linked_taginfo G__EventDictLN_TObject;
extern G__linked_taginfo G__EventDictLN_vectorlElongcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__EventDictLN_string;
extern G__linked_taginfo G__EventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_RowColumnEntry;
extern G__linked_taginfo G__EventDictLN_vectorlERowColumnEntrymUcOallocatorlERowColumnEntrymUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlERowColumnEntrymUcOallocatorlERowColumnEntrymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_TestBeamEventElement;
extern G__linked_taginfo G__EventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TH1D;
extern G__linked_taginfo G__EventDictLN_TH1F;
extern G__linked_taginfo G__EventDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_listlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlERowColumnEntrycOallocatorlERowColumnEntrygRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlERowColumnEntrycOallocatorlERowColumnEntrygRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOvectorlERowColumnEntrycOallocatorlERowColumnEntrygRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlERowColumnEntrycOallocatorlERowColumnEntrygRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOAlignmentParametersmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOAlignmentParametersmUgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_TDCTrigger;
extern G__linked_taginfo G__EventDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlETDCTriggermUcOallocatorlETDCTriggermUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETDCTriggermUcOallocatorlETDCTriggermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_TDCFrame;
extern G__linked_taginfo G__EventDictLN_vectorlETDCFramemUcOallocatorlETDCFramemUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETDCFramemUcOallocatorlETDCFramemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_TestBeamEvent;
extern G__linked_taginfo G__EventDictLN_vectorlETestBeamEventElementcOallocatorlETestBeamEventElementgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETestBeamEventElementcOallocatorlETestBeamEventElementgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_vectorlETDCFramecOallocatorlETDCFramegRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETDCFramecOallocatorlETDCFramegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_FEI4RowColumnEntry;
extern G__linked_taginfo G__EventDictLN_vectorlEFEI4RowColumnEntrymUcOallocatorlEFEI4RowColumnEntrymUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEFEI4RowColumnEntrymUcOallocatorlEFEI4RowColumnEntrymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_TestBeamDataSummary;
extern G__linked_taginfo G__EventDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOTH1DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1DmUgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOTH1FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1FmUgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_SystemOfUnits;
extern G__linked_taginfo G__EventDictLN_PhysicalConstants;

/* STUB derived class for protected member access */
