/********************************************************************
* core/EventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error core/EventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEventDict();
extern void G__cpp_setup_inheritanceEventDict();
extern void G__cpp_setup_typetableEventDict();
extern void G__cpp_setup_memvarEventDict();
extern void G__cpp_setup_globalEventDict();
extern void G__cpp_setup_memfuncEventDict();
extern void G__cpp_setup_funcEventDict();
extern void G__set_cpp_environmentEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/Users/danielhynds/work/hvcmos/newTBcode/objs/Pixel.h"
#include "/Users/danielhynds/work/hvcmos/newTBcode/objs/TestBeamObject.h"
#include "/Users/danielhynds/work/hvcmos/newTBcode/objs/Timepix3Cluster.h"
#include "/Users/danielhynds/work/hvcmos/newTBcode/objs/Timepix3Pixel.h"
#include "/Users/danielhynds/work/hvcmos/newTBcode/objs/Timepix3Track.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventDictLN_TClass;
extern G__linked_taginfo G__EventDictLN_TBuffer;
extern G__linked_taginfo G__EventDictLN_TMemberInspector;
extern G__linked_taginfo G__EventDictLN_TObject;
extern G__linked_taginfo G__EventDictLN_ROOT;
extern G__linked_taginfo G__EventDictLN_string;
extern G__linked_taginfo G__EventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_TestBeamObject;
extern G__linked_taginfo G__EventDictLN_vectorlETestBeamObjectmUcOallocatorlETestBeamObjectmUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETestBeamObjectmUcOallocatorlETestBeamObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_Pixel;
extern G__linked_taginfo G__EventDictLN_vectorlEPixelmUcOallocatorlEPixelmUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEPixelmUcOallocatorlEPixelmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_Timepix3Pixel;
extern G__linked_taginfo G__EventDictLN_vectorlETimepix3PixelmUcOallocatorlETimepix3PixelmUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETimepix3PixelmUcOallocatorlETimepix3PixelmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_Timepix3Cluster;
extern G__linked_taginfo G__EventDictLN_vectorlETimepix3ClustermUcOallocatorlETimepix3ClustermUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETimepix3ClustermUcOallocatorlETimepix3ClustermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EventDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EventDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EventDictLN_TLinearFitter;
extern G__linked_taginfo G__EventDictLN_ROOTcLcLMath;
extern G__linked_taginfo G__EventDictLN_ROOTcLcLMathcLcLPositionVector3DlEROOTcLcLMathcLcLCartesian3DlEdoublegRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR;
extern G__linked_taginfo G__EventDictLN_ROOTcLcLMathcLcLDisplacementVector3DlEROOTcLcLMathcLcLCartesian3DlEdoublegRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR;
extern G__linked_taginfo G__EventDictLN_Timepix3Track;
extern G__linked_taginfo G__EventDictLN_vectorlETimepix3TrackmUcOallocatorlETimepix3TrackmUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETimepix3TrackmUcOallocatorlETimepix3TrackmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
